### PR TITLE
Allow setting update password

### PR DESCRIPTION
**Pull request by o-sole-meo**
This adds the setting "update_password" from the user role so password updates/resets for already created users can be deactivated.

### CODE REVIEW

**Comment by dennisconrad** [comment]
Hi there, and thank you for the PR!  Can you please squash your two commits into one, as described here?  http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by o-sole-meo** [comment]
hello! thanks for that very convenient role!
I think this is fixed now, could you please check again?

**Review by dennisconrad — APPROVED** [review]

**Review by lobsterdore — APPROVED** [review]
LGTM 👍

**Comment by lobsterdore** [comment]
@o-sole-meo your changes are out in version 2.0.5 - https://galaxy.ansible.com/sansible/users_and_groups

**Comment by o-sole-meo** [comment]
great, thanks!

**Pull request merged**
